### PR TITLE
change the standard format for each error

### PR DESCRIPTION
**Pull request by Gyrosona**

### CODE REVIEW

**Review by alicerunsonfedora — CHANGES_REQUESTED** [review]
While I do approve of the bolding of items, I don't necessarily approve of removing the RenPy category or putting everything in all caps.

**Comment by Gyrosona** [comment]
wait what

**Comment by Gyrosona** [comment]
hudiawdawdfafawfijoawfjoaiwfj HOW DO I USE THIS PULL REQUEST SHIIIIT

**Comment by alicerunsonfedora** [comment]
Haha, you just merged the PR

**Comment by Gyrosona** [comment]
im stupid lol

**Comment by sr229** [comment]
Reverting this PR

**Pull request merged**
